#ifndef SIZE_OFFSETS_H
#define SIZE_OFFSETS_H


// Primitive sizes
#define UINT8_SIZE 1
#define UINT16_SIZE 2
#define UINT32_SIZE 4
#define UINT64_SIZE 8
#define UINT256_SIZE 32
#define UINT512_SIZE 64


//STRUCTS SIZES

#define TRUST_NODE_SIZE 28
#define IPV6_SIZE 16

#define CERT_SIZE (UINT8_SIZE + 2 * UINT256_SIZE + 3 * UINT8_SIZE)                            // 1 + 32 + 32 + 1+1+1 = 68
#define BLOCK_SIZE (CERT_SIZE + 2 * UINT256_SIZE + UINT512_SIZE + 2 * UINT64_SIZE + 4 * UINT8_SIZE) // 68 + 32 + 32 + 64 + 2*8 + 4 = 216
#define BLOCK_SERIALIZED_SIZE (BLOCK_SIZE + MINI_POW_RESULT_SERIALIZED_SIZE + TIER_POW_RESULT_SERIALIZED_SIZE)
#define PK_CERT_CHAIN_SIZE (100 * BLOCK_SIZE + UINT32_SIZE) // 100 blocks + index (serialized size)

#define MINI_POW_CHALLENGE_SIZE (UINT64_SIZE + 3 * UINT16_SIZE) // 14 bytes
#define MINI_POW_SOLVE_SIZE (3 * UINT16_SIZE + 3 * UINT64_SIZE) // 30 bytes
#define TIER_POW_CHALLENGE_SIZE (UINT256_SIZE + UINT8_SIZE + UINT64_SIZE + 3 * UINT8_SIZE) // 44 bytes
#define TIER_POW_SOLVE_SIZE (UINT64_SIZE + UINT8_SIZE + UINT64_SIZE + 3 * UINT8_SIZE) // 20 bytes
#define TIER_POW_CHALLENGE_SERIALIZED_SIZE TIER_POW_CHALLENGE_SIZE
#define TIER_POW_SOLVE_SERIALIZED_SIZE TIER_POW_SOLVE_SIZE
#define MINI_POW_RESULT_SERIALIZED_SIZE 12
#define TIER_POW_RESULT_SERIALIZED_SIZE 76

#define MINI_POW_MATRIX_N 10


#endif // SIZE_OFFSETS_H
