CREATE TABLE IF NOT EXISTS networks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    network_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    bootstrap_url VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(50),
    active TINYINT(1) DEFAULT 1,
    active_peers INT DEFAULT 0,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);