#pragma once

#include <stdint.h>

enum PacketStatus : uint16_t
{
    PACKET_STATUS_NONE = 0,

    PACKET_STATUS_OK,

    PACKET_STATUS_INVALID_SIGNATURE,
    PACKET_STATUS_INVALID_HASH,
    PACKET_STATUS_TIMEOUT,
    PACKET_STATUS_BUSY,
    PACKET_STATUS_UNSUPPORTED,
    PACKET_STATUS_ROUTE_FAILURE,
    PACKET_STATUS_DUPLICATE,
    PACKET_STATUS_TAMPERED
};